
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x84400000
#define STDOUT_BASEADDRESS 0x84400000
/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 3

/* Definitions for peripheral LEDS_4BIT */
#define XPAR_LEDS_4BIT_BASEADDR 0x81440000
#define XPAR_LEDS_4BIT_HIGHADDR 0x8144FFFF
#define XPAR_LEDS_4BIT_DEVICE_ID 0
#define XPAR_LEDS_4BIT_INTERRUPT_PRESENT 0
#define XPAR_LEDS_4BIT_IS_DUAL 0


/* Definitions for peripheral LEDS_POSITIONS */
#define XPAR_LEDS_POSITIONS_BASEADDR 0x81420000
#define XPAR_LEDS_POSITIONS_HIGHADDR 0x8142FFFF
#define XPAR_LEDS_POSITIONS_DEVICE_ID 1
#define XPAR_LEDS_POSITIONS_INTERRUPT_PRESENT 0
#define XPAR_LEDS_POSITIONS_IS_DUAL 0


/* Definitions for peripheral PUSH_BUTTONS_POSITION */
#define XPAR_PUSH_BUTTONS_POSITION_BASEADDR 0x81400000
#define XPAR_PUSH_BUTTONS_POSITION_HIGHADDR 0x8140FFFF
#define XPAR_PUSH_BUTTONS_POSITION_DEVICE_ID 2
#define XPAR_PUSH_BUTTONS_POSITION_INTERRUPT_PRESENT 0
#define XPAR_PUSH_BUTTONS_POSITION_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral LEDS_4BIT */
#define XPAR_GPIO_0_BASEADDR 0x81440000
#define XPAR_GPIO_0_HIGHADDR 0x8144FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_LEDS_4BIT_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral LEDS_POSITIONS */
#define XPAR_GPIO_1_BASEADDR 0x81420000
#define XPAR_GPIO_1_HIGHADDR 0x8142FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_LEDS_POSITIONS_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0

/* Canonical definitions for peripheral PUSH_BUTTONS_POSITION */
#define XPAR_GPIO_2_BASEADDR 0x81400000
#define XPAR_GPIO_2_HIGHADDR 0x8140FFFF
#define XPAR_GPIO_2_DEVICE_ID XPAR_PUSH_BUTTONS_POSITION_DEVICE_ID
#define XPAR_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_GPIO_2_IS_DUAL 0


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral MDM_0 */
#define XPAR_MDM_0_BASEADDR 0x84400000
#define XPAR_MDM_0_HIGHADDR 0x8440FFFF
#define XPAR_MDM_0_DEVICE_ID 0
#define XPAR_MDM_0_BAUDRATE 0
#define XPAR_MDM_0_USE_PARITY 0
#define XPAR_MDM_0_ODD_PARITY 0
#define XPAR_MDM_0_DATA_BITS 0


/******************************************************************/

/* Canonical definitions for peripheral MDM_0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_MDM_0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x84400000
#define XPAR_UARTLITE_0_HIGHADDR 0x8440FFFF
#define XPAR_UARTLITE_0_BAUDRATE 0
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 0
#define XPAR_UARTLITE_0_SIO_CHAN -1


/******************************************************************/


/* Definitions for peripheral MY_NEWIP_22_0 */
#define XPAR_MY_NEWIP_22_0_BASEADDR 0xC2400000
#define XPAR_MY_NEWIP_22_0_HIGHADDR 0xC240FFFF


/******************************************************************/


/* Definitions for peripheral SRAM */
#define XPAR_SRAM_NUM_BANKS_MEM 1


/******************************************************************/

/* Definitions for peripheral SRAM */
#define XPAR_SRAM_MEM0_BASEADDR 0x00000000
#define XPAR_SRAM_MEM0_HIGHADDR 0x000FFFFF

/******************************************************************/

/* Canonical definitions for peripheral SRAM */
#define XPAR_EMC_0_NUM_BANKS_MEM 1
#define XPAR_EMC_0_MEM0_BASEADDR 0x00000000
#define XPAR_EMC_0_MEM0_HIGHADDR 0x000FFFFF

#define XPAR_XPS_MCH_EMC

/******************************************************************/

#define XPAR_XSYSACE_MEM_WIDTH 16
/* Definitions for driver SYSACE */
#define XPAR_XSYSACE_NUM_INSTANCES 1

/* Definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_COMPACTFLASH_DEVICE_ID 0
#define XPAR_SYSACE_COMPACTFLASH_BASEADDR 0x83600000
#define XPAR_SYSACE_COMPACTFLASH_HIGHADDR 0x8360FFFF
#define XPAR_SYSACE_COMPACTFLASH_MEM_WIDTH 16


/******************************************************************/

/* Canonical definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_0_DEVICE_ID XPAR_SYSACE_COMPACTFLASH_DEVICE_ID
#define XPAR_SYSACE_0_BASEADDR 0x83600000
#define XPAR_SYSACE_0_HIGHADDR 0x8360FFFF
#define XPAR_SYSACE_0_MEM_WIDTH 16


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral XPS_BRAM_IF_CNTLR_1 */
#define XPAR_XPS_BRAM_IF_CNTLR_1_DEVICE_ID 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_DATA_WIDTH 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_FAULT_INJECT 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_CE_FAILING_REGISTERS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_UE_FAILING_REGISTERS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC_STATUS_REGISTERS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_CE_COUNTER_WIDTH 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC_ONOFF_REGISTER 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_WRITE_ACCESS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_BASEADDR 0xFFFFE000
#define XPAR_XPS_BRAM_IF_CNTLR_1_HIGHADDR 0xFFFFFFFF


/******************************************************************/

/* Canonical definitions for peripheral XPS_BRAM_IF_CNTLR_1 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_XPS_BRAM_IF_CNTLR_1_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 0
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_0_WRITE_ACCESS 0
#define XPAR_BRAM_0_BASEADDR 0xFFFFE000
#define XPAR_BRAM_0_HIGHADDR 0xFFFFFFFF


/******************************************************************/

/* Definitions for driver WDTTB */
#define XPAR_XWDTTB_NUM_INSTANCES 1

/* Definitions for peripheral XPS_TIMEBASE_WDT_0 */
#define XPAR_XPS_TIMEBASE_WDT_0_DEVICE_ID 0
#define XPAR_XPS_TIMEBASE_WDT_0_BASEADDR 0x83A00000
#define XPAR_XPS_TIMEBASE_WDT_0_HIGHADDR 0x83A0FFFF


/******************************************************************/

/* Canonical definitions for peripheral XPS_TIMEBASE_WDT_0 */
#define XPAR_WDTTB_0_DEVICE_ID XPAR_XPS_TIMEBASE_WDT_0_DEVICE_ID
#define XPAR_WDTTB_0_BASEADDR 0x83A00000
#define XPAR_WDTTB_0_HIGHADDR 0x83A0FFFF


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral XPS_TIMER_0 */
#define XPAR_XPS_TIMER_0_DEVICE_ID 0
#define XPAR_XPS_TIMER_0_BASEADDR 0x83C00000
#define XPAR_XPS_TIMER_0_HIGHADDR 0x83C0FFFF
#define XPAR_XPS_TIMER_0_CLOCK_FREQ_HZ 100000000


/******************************************************************/

/* Canonical definitions for peripheral XPS_TIMER_0 */
#define XPAR_TMRCTR_0_DEVICE_ID XPAR_XPS_TIMER_0_DEVICE_ID
#define XPAR_TMRCTR_0_BASEADDR 0x83C00000
#define XPAR_TMRCTR_0_HIGHADDR 0x83C0FFFF
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_XPS_TIMER_0_CLOCK_FREQ_HZ

/******************************************************************/

/* Definition for PPC cacheable regions */
#define XPAR_CACHEABLE_REGION_MASK 0x80000001
/******************************************************************/

/* Definitions for bus frequencies */
#define XPAR_CPU_PPC405_DPLB0_FREQ_HZ 100000000
#define XPAR_CPU_PPC405_IPLB0_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
#define XPAR_PROC_BUS_0_FREQ_HZ 100000000
/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_PPC405_VIRTEX4_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_PPC405_VIRTEX4_ID 0
#define XPAR_PPC405_VIRTEX4_DPLB0_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB0_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB1_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB1_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_VIRTEX4_DPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_VIRTEX4_IPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_VIRTEX4_IPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_VIRTEX4_FASTEST_PLB_CLOCK DPLB0
#define XPAR_PPC405_VIRTEX4_GENERATE_PLB_TIMESPECS 1
#define XPAR_PPC405_VIRTEX4_DPLB0_P2P 0
#define XPAR_PPC405_VIRTEX4_DPLB1_P2P 1
#define XPAR_PPC405_VIRTEX4_IPLB0_P2P 0
#define XPAR_PPC405_VIRTEX4_IPLB1_P2P 1
#define XPAR_PPC405_VIRTEX4_IDCR_BASEADDR 0x00000100
#define XPAR_PPC405_VIRTEX4_IDCR_HIGHADDR 0x000001FF
#define XPAR_PPC405_VIRTEX4_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_VIRTEX4_MMU_ENABLE 1
#define XPAR_PPC405_VIRTEX4_DETERMINISTIC_MULT 0
#define XPAR_PPC405_VIRTEX4_PLBSYNCBYPASS 1
#define XPAR_PPC405_VIRTEX4_APU_CONTROL 0b1101111000000000
#define XPAR_PPC405_VIRTEX4_APU_UDI_1 0b101000011000100110000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_2 0b101000111000100110000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_3 0b101001011000100111000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_4 0b101001111000100111000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_5 0b101010011000110000000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_6 0b101010111000110000000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_7 0b101011011000110001000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_8 0b101011111000110001000011
#define XPAR_PPC405_VIRTEX4_PVR_HIGH 0b0000
#define XPAR_PPC405_VIRTEX4_PVR_LOW 0b0000
#define XPAR_PPC405_VIRTEX4_HW_VER "2.01.b"

/******************************************************************/

#define XILFATFS_MAXFILES 5
#define XILFATFS_BUFCACHE_SIZE 10240
